# Phase 2: Data Enrichment (Open Food Facts API)

In this phase, we will take our cleaned list of Indian FMCG products and query the Open Food Facts API to find their international counterparts and ingredients.

In [13]:
import pandas as pd
import requests

# loading csv file
df=pd.read_csv("data/multinational_brand_cleaned.csv")
print(f"Dataset loaded successfully!\nTotal products: {len(df)}")

Dataset loaded successfully!
Total products: 172

In [14]:
df.head(10)

,Priority_Rank,S.No,Item name,Brand_Name,Category,Sub_Category,Ingredients,Serving_Size_g,Sugar_g,Total_Fat_g,OFF_UK_Barcode,OFF_UK_Match_Found_Y_N,Indian_Label_Verified_Y_N,Verification_Source_URL,Notes
0,1,184,7 Up Lemon Soft Drink,7 UP,JUICE,SODA,"Carbonated Water, Sugar, Acidity Regulators (3...",100.0,11.7,0,NaN,NaN,NaN,NaN,NaN
1,2,185,7UP Nimbooz Soft Drink,7 UP NIMBOOZ,JUICE,SODA,"Water, Sugar, Concentrated Lemon Juice (0.7%),...",100.0,10.6,0,NaN,NaN,NaN,NaN,NaN
2,3,705,Betty Crocker Triple Chocolate Brownie Instant...,BETTY CROCKER,INSTANT FOOD,CAKE MIX,"Sugar, Refined Wheat Flour (Maida), Cocoa Powd...",100.0,54.3,4.6,NaN,NaN,NaN,NaN,NaN
3,4,593,Bournvita Biscuits,CADBURY,BISCUIT,BISCUIT,"Refined Wheat Flour (Maida) (56%), Sugar, Palm...",100.0,28.3,15.3,NaN,NaN,NaN,NaN,NaN
4,5,391,Bounty Miniatures Coconut Filled Chocolate Pack,BOUNTY,CHOCOLATE,CHOCOLATE BAR,"Milk chocolate coating (44%) (Sugar, Milk soli...",100.0,50,25.8,NaN,NaN,NaN,NaN,NaN
5,6,401,Cadbury Bournville Cranberry 50% Dark CHOCOLAT...,CADBURY,CHOCOLATE,CHOCOLATE BAR,"Sugar, Cocoa Butter (24%), Cocoa Solids (18%),...",100.0,45.7,31.6,NaN,NaN,NaN,NaN,NaN
6,7,402,Cadbury Bournville Fruit & Nut 50% Dark CHOCOL...,CADBURY,CHOCOLATE,CHOCOLATE BAR,"Sugar, Cocoa Butter (24%), Cocoa Solids (18%),...",100.0,44.2,32.8,NaN,NaN,NaN,NaN,NaN
7,8,400,Cadbury Bournville Rich Cocoa 70% Dark CHOCOLA...,CADBURY,CHOCOLATE,CHOCOLATE BAR,"Cocoa Butter, Cocoa Solids, Emulsifiers (442, ...",100.0,20.4,47.4,NaN,NaN,NaN,NaN,NaN
8,9,386,Cadbury Temptations Almond Treat Premium CHOCO...,CADBURY,CHOCOLATE,CHOCOLATE BAR,"Sugar, Almonds (17%), Cocoa Butter, Milk Solid...",100.0,45.2,35,NaN,NaN,NaN,NaN,NaN
9,10,389,Cadbury Temptations Rum & Raisins Premium CHOC...,CADBURY,CHOCOLATE,CHOCOLATE,"Sugar, Raisins (18%), Cocoa Butter, Cocoa Soli...",100.0,57,26,NaN,NaN,NaN,NaN,NaN

In [15]:
df[['Brand_Name', 'Item name']]

        Brand_Name                                          Item name
0             7 UP                              7 Up Lemon Soft Drink
1     7 UP NIMBOOZ                             7UP Nimbooz Soft Drink
2    BETTY CROCKER  Betty Crocker Triple Chocolate Brownie Instant...
3          CADBURY                                 Bournvita Biscuits
4           BOUNTY    Bounty Miniatures Coconut Filled Chocolate Pack
..             ...                                                ...
167      TROPICANA            Tropicana Delight Cranberry Fruit Juice
168      TROPICANA                Tropicana Delight Guava Fruit Juice
169      TROPICANA                Tropicana Delight Mixed Fruit Juice
170           TWIX           Twix Minis Cookie Caramel Chocolate Pack
171          WEDEL                           Wedel Milk CHOCOLATE BAR

[172 rows x 2 columns]

In [46]:
# Test API Request on 1 single product ("7UP")
url = "https://world.openfoodfacts.org/cgi/search.pl"
params = {
    "search_terms" :"7 Up Lemon Soft Drink",
    "search_simple": 1,
    "action": "process",
    "json": 1, #1 means to return the json data not webpage
    "page_size": 10 #just bring 3 results for now
}

# 3. Set User-Agent header (Identifies our project so we don't get blocked as a bot)
headers = {
    "User-Agent": "CrossBorderIngredientPlatform/1.0 (student_research_project)"
}

# 4. Send the GET request over the internet
response = requests.get(url, params=params, headers=headers)
# 5. Check response status code (200 = Success!)
print("HTTP Status Code:", response.status_code)
# 6. Convert response to Python Dictionary
data = response.json() # in this I have multiple items of 7UP

# Print total matches found in Open Food Facts database
#Safe JSON parsing: Using .get('count', 0) is excellent defensive programming. 
# If the API fails and the count key doesn't exist, your code will gracefully return 0 instead of throwing a KeyError and crashing.
print("Total matches found:", data.get('count', 0))

HTTP Status Code: 200
Total matches found: 6

In [47]:
# Inspect the 1st product from our search results
# 1. Get the list of products from our response data dictionary
products=data.get("products",[])
print(f"Number of products returned in this page: {len(products)}\n")

first_product = products[0]

# 3. Extract the key fields we care about
name = first_product.get("product_name", "No Name Found")
barcode = first_product.get("code", "No Barcode")
countries = first_product.get("countries_tags", [])
ingredients = first_product.get("ingredients_text", "No Ingredients Text Found")
# 4. Print the extracted details nicely
print(f"=== 1st Product Found ===")
print(f"Product Name : {name}")
print(f"Barcode      : {barcode}")
print(f"Countries    : {countries}")
print(f"\nIngredients Text:\n{ingredients}")

Number of products returned in this page: 6

=== 1st Product Found ===
Product Name : 7 up
Barcode      : 5410188033809
Countries    : ['en:belgium', 'en:france']

Ingredients Text:
eau gazéifiée, sucre, acidifiants (acide citrique adle malique) aromes naturels de citron et de citron vert, coredelt daddite (citrate de sodium), édulcorant (glycosides de teviol!

In [37]:
# We searched Open Food Facts for "7 Up".
# Open Food Facts did a simple word match and gave us a product named "press up jaouda petit orange" from Morocco! Why? Because "press up" contains the letters "up".
# This is not the 7 Up soda soft drink we wanted!

In [38]:
# If we just naively took products[0] (the very 1st result), we would accidentally pair Indian 7-Up soda with a Moroccan Orange Juice!

# This is why our code needs Smart Filtering Logic:
# When Open Food Facts returns a list of results, we should loop through them and pick the product that:
        # Has a valid ingredients_text (is not empty).
        # Is sold in the UK / Europe / International (e.g. 'en:united-kingdom', 'en:united-states', 'en:france', etc.).

In [48]:
# Cell 4: Loop through all 3 returned products to find the best UK/EU match

print("=== Scanning All Results for a UK/EU Match ===\n")

for i, product in enumerate(products):
    p_name = product.get("product_name", "No Name")
    countries = product.get("countries_tags", [])
    ingredients = product.get("ingredients_text", "")
    
    print(f"Product #{i+1}: {p_name}")
    print(f"  Countries : {countries}")
    print(f"  Has Ingredients? {'Yes' if ingredients else 'No'}")
    print("-" * 50)

=== Scanning All Results for a UK/EU Match ===

Product #1: 7 up
  Countries : ['en:belgium', 'en:france']
  Has Ingredients? Yes
--------------------------------------------------
Product #2: 7 Up tasty twist lemon and lime
  Countries : ['en:united-kingdom']
  Has Ingredients? Yes
--------------------------------------------------
Product #3: Lemon Lime Soda
  Countries : ['en:united-states']
  Has Ingredients? Yes
--------------------------------------------------
Product #4: 7 up free
  Countries : ['en:france', 'en:united-kingdom']
  Has Ingredients? Yes
--------------------------------------------------
Product #5: Seven up
  Countries : ['en:senegal']
  Has Ingredients? Yes
--------------------------------------------------
Product #6: Seven Up
  Countries : ['en:united-arab-emirates']
  Has Ingredients? Yes
--------------------------------------------------

In [61]:
# Cell 5: Version 4 - Waterfall Search Strategy (Think like a Human Analyst!)

NOISE_WORDS = {
    'chocolate', 'bar', 'soft', 'drink', 'flavour', 'flavored', 'flavoured',
    'potato', 'chips', 'pack', 'premium', 'imported', 'instant', 'energy',
    'mini', 'treats', 'candy', 'toffee', 'biscuit', 'wafer', 'delights',
    'crispy', 'original', 'classic', 'special', 'new', 'limited', 'edition'
}

def build_search_queries(brand_name, item_name):
    clean_item = str(item_name).replace('\xa0', ' ').replace('&', 'and').strip()
    
    all_words = clean_item.split()
    core_words = [w for w in all_words if w.lower().rstrip('s') not in NOISE_WORDS]
    
    queries = []
    
    # Query 1: Full item name
    queries.append(clean_item)
    
    # Query 2: First 4 words
    if len(all_words) > 4:
        queries.append(" ".join(all_words[:4]))
        
    # Query 3: First 3 core words
    if core_words and len(core_words) >= 3:
        queries.append(" ".join(core_words[:3]))
        
    # Query 4: First 2 core words (e.g. "Snickers Peanut", "Betty Crocker")
    if core_words and len(core_words) >= 2:
        queries.append(" ".join(core_words[:2]))
        
    # Query 5: Brand + first core word
    core_brand = brand_name.title()
    if core_words:
        queries.append(f"{core_brand} {core_words[0]}")
    
    # Remove duplicates while preserving order
    seen = set()
    unique_queries = []
    for q in queries:
        q_clean = q.strip()
        if q_clean and q_clean not in seen:
            seen.add(q_clean)
            unique_queries.append(q_clean)
            
    return unique_queries


def search_off_api(query, page_size=15):
    """
    ONE single API call for a given query.
    Returns a list of products or empty list.
    """
    url = "https://world.openfoodfacts.org/cgi/search.pl"
    params = {
        "search_terms": query,
        "search_simple": 1,
        "action": "process",
        "json": 1,
        "page_size": page_size
    }
    headers = {"User-Agent": "CrossBorderIngredientPlatform/1.0 (student_project)"}
    try:
        response = requests.get(url, params=params, headers=headers, timeout=8)
        if response.status_code == 200:
            return response.json().get("products", [])
    except Exception:
        pass
    return []


def pick_best_product(products):
    """
    From a list of products, pick the best one.
    Priority: UK → US/EU → Any country with ingredients.
    """
    PRIORITY_COUNTRIES = ["united-kingdom", "united-states", "france", "germany", "australia", "canada"]
    
    # Pass 1: Look for UK product
    for p in products:
        countries = str(p.get("countries_tags", [])).lower()
        ingredients = p.get("ingredients_text", "")
        if "united-kingdom" in countries and ingredients and len(ingredients.strip()) > 5:
            return p
    
    # Pass 2: Look for other priority countries
    for country in PRIORITY_COUNTRIES[1:]:
        for p in products:
            countries = str(p.get("countries_tags", [])).lower()
            ingredients = p.get("ingredients_text", "")
            if country in countries and ingredients and len(ingredients.strip()) > 5:
                return p
    
    # Pass 3: Any product with valid ingredients (last resort)
    for p in products:
        ingredients = p.get("ingredients_text", "")
        if ingredients and len(ingredients.strip()) > 5:
            return p
    
    return None


def fetch_uk_ingredients_smart(brand_name, item_name):
    """
    MAIN FUNCTION: Waterfall Search Strategy.
    Tries multiple queries like a human analyst until a match is found.
    """
    queries = build_search_queries(brand_name, item_name)
    
    for query in queries:
        products = search_off_api(query)
        best = pick_best_product(products)
        if best:
            return {
                "OFF_Match_Found": "Yes",
                "OFF_UK_Barcode": best.get("code"),
                "OFF_UK_Ingredients": best.get("ingredients_text", "")
            }
    
    return {"OFF_Match_Found": "No", "OFF_UK_Barcode": None, "OFF_UK_Ingredients": None}


# ---- Quick Test of all 3 problem products ----
print("Test 1 - 7 Up:")
print(fetch_uk_ingredients_smart("7 UP", "7 Up Lemon Soft Drink"))

print("\nTest 2 - Snickers:")
print(fetch_uk_ingredients_smart("MARS", "Snickers Peanut Filled CHOCOLATE BAR"))

print("\nTest 3 - KitKat:")
print(fetch_uk_ingredients_smart("NESTLE", "Nestle KitKat Delights Dark"))

print("\nTest 4 - Coca-Cola Zero:")
print(fetch_uk_ingredients_smart("COCA-COLA", "Coca-Cola Zero Sugar Soft Drink"))

Test 1 - 7 Up:
{'OFF_Match_Found': 'No', 'OFF_UK_Barcode': None, 'OFF_UK_Ingredients': None}

Test 2 - Snickers:
{'OFF_Match_Found': 'Yes', 'OFF_UK_Barcode': '5000159550345', 'OFF_UK_Ingredients': 'Sugar, glucose syrup, peanuts, skimmed milk powder, cocoa butter, cocoa mass, sunflower oil, palm fat, whey permeate (milk), milk fat, salt, emulsifier (soya lecithin) egg white powder.'}

Test 3 - KitKat:
{'OFF_Match_Found': 'Yes', 'OFF_UK_Barcode': '3387390123210', 'OFF_UK_Ingredients': "Farine de BLÉ complet 37,5 %, farine de BLÉ 18,5 %, chocolat en poudre 18,1 % (sucre, cacao en poudre*), semoule de maïs, sirop de glucose, extrait de malt d'ORGE (ORGE, ORGE malté), huile de tournesol, carbonate de calcium, sucre, farine d'ORGE malté, émulsifiant : lécithines ; sel, arômes naturels, fer, vitamines B3, B5, D, B6, B1, B2, B9. Peut contenir du LAIT et des FRUITS À COQUE."}

Test 4 - Coca-Cola Zero:
{'OFF_Match_Found': 'Yes', 'OFF_UK_Barcode': '5449000131805', 'OFF_UK_Ingredients': 'carbonated water, colour (e150d), acid (phosphoric acid) sweeteners (aspartame, acesulfame-k enzymatically produced steviol glycosides), natural flavourings, caffeine flavouring, acidity regulator (sodium citrates), contains a source of phenylalanine,'}

In [62]:
# Cell 6: Step 5 & 6 - Batch Process All 172 Products using Waterfall Search & Export

import time

print(f"🚀 Starting Batch API Lookup (Waterfall Strategy) for {len(df)} products...\n")

match_status = []
barcodes = []
uk_ingredients = []

for index, row in df.iterrows():
    brand = row['Brand_Name']
    item = row['Item name']
    
    print(f"[{index + 1}/{len(df)}] Searching: {item[:35]}...", end=" ")
    
    # Call our Waterfall Search function (tries multiple queries like a human)
    result = fetch_uk_ingredients_smart(brand, item)
    
    match_status.append(result['OFF_Match_Found'])
    barcodes.append(result['OFF_UK_Barcode'])
    uk_ingredients.append(result['OFF_UK_Ingredients'])
    
    if result['OFF_Match_Found'] == 'Yes':
        print("✅ MATCH FOUND!")
    else:
        print("❌ Not Found")
        
    # Polite sleep to respect API rate limits
    time.sleep(0.4)

# 1. Update DataFrame columns
df['OFF_UK_Match_Found_Y_N'] = match_status
df['OFF_UK_Barcode'] = barcodes
df['OFF_UK_Ingredients'] = uk_ingredients

# 2. Print Match Summary
total_matches = (df['OFF_UK_Match_Found_Y_N'] == 'Yes').sum()
print("\n" + "="*50)
print(f"🎉 BATCH LOOKUP COMPLETE!")
print(f"Successfully Matched: {total_matches} / {len(df)} products ({(total_matches/len(df))*100:.1f}%)")
print("="*50 + "\n")

# 3. Save Final Files
df.to_csv('data/multinational_brand_enriched.csv', index=False)
df.to_json('data/benchmark_candidates.json', orient='records', indent=4)
print("💾 Enriched datasets saved to data/multinational_brand_enriched.csv and data/benchmark_candidates.json!")

🚀 Starting Batch API Lookup (Waterfall Strategy) for 172 products...

[1/172] Searching: 7 Up Lemon Soft Drink... ✅ MATCH FOUND!
[2/172] Searching: 7UP Nimbooz Soft Drink... ✅ MATCH FOUND!
[3/172] Searching: Betty Crocker Triple Chocolate Brow... ✅ MATCH FOUND!
[4/172] Searching: Bournvita Biscuits... ❌ Not Found
[5/172] Searching: Bounty Miniatures Coconut Filled Ch... ❌ Not Found
[6/172] Searching: Cadbury Bournville Cranberry 50% Da... ✅ MATCH FOUND!
[7/172] Searching: Cadbury Bournville Fruit & Nut 50% ... ✅ MATCH FOUND!
[8/172] Searching: Cadbury Bournville Rich Cocoa 70% D... ✅ MATCH FOUND!
[9/172] Searching: Cadbury Temptations Almond Treat Pr... ✅ MATCH FOUND!
[10/172] Searching: Cadbury Temptations Rum & Raisins P... ✅ MATCH FOUND!
[11/172] Searching: Bournvita Chocolate... ✅ MATCH FOUND!
[12/172] Searching: Cadbury 5 Star 3D CHOCOLATE BAR... ✅ MATCH FOUND!
[13/172] Searching: Cadbury 5 Star CHOCOLATE BAR... ✅ MATCH FOUND!
[14/172] Searching: Cadbury Bournville Rich Cocoa 50% D... ✅ MATCH FOUND!
[15/172] Searching: Cadbury Choclairs Gold Candy... ❌ Not Found
[16/172] Searching: Cadbury Dairy Milk Bites Hazelnut C... ✅ MATCH FOUND!
[17/172] Searching: Cadbury Dairy Milk Chocolate Bar... ✅ MATCH FOUND!
[18/172] Searching: Cadbury Dairy Milk Crispello CHOCOL... ✅ MATCH FOUND!
[19/172] Searching: Cadbury Dairy Milk Fruit & Nut CHOC... ✅ MATCH FOUND!
[20/172] Searching: Cadbury Dairy Milk Lickables Chocol... ✅ MATCH FOUND!
[21/172] Searching: Cadbury Dairy Milk Silk Bubbly CHOC... ✅ MATCH FOUND!
[22/172] Searching: Cadbury Dairy Milk Silk CHOCOLATE B... ✅ MATCH FOUND!
[23/172] Searching: Cadbury Dairy Milk Silk Desserts Br... ❌ Not Found
[24/172] Searching: Cadbury Dairy Milk Silk Desserts Pl... ✅ MATCH FOUND!
[25/172] Searching: Cadbury Dairy Milk Silk Hazelnut CH... ✅ MATCH FOUND!
[26/172] Searching: Cadbury Dairy Milk Silk Mousse CHOC... ✅ MATCH FOUND!
[27/172] Searching: Cadbury Dairy Milk Silk Oreo CHOCOL... ❌ Not Found
[28/172] Searching: Cadbury Fuse Mini Treats Chocolate ... ✅ MATCH FOUND!
[29/172] Searching: Cadbury Gems Chocolate Mini Treats ... ✅ MATCH FOUND!
[30/172] Searching: Cadbury Gems Surprise Ball Chocolat... ✅ MATCH FOUND!
[31/172] Searching: Cadbury Nutties Chocolate... ✅ MATCH FOUND!
[32/172] Searching: Cadbury Oreo Original Chocolatey Sa... ✅ MATCH FOUND!
[33/172] Searching: Cadbury Perk Mini Treats Chocolate ... ❌ Not Found
[34/172] Searching: Cheetos Masala PUFFS, Crispy Chips ... ✅ MATCH FOUND!
[35/172] Searching: Coca-Cola Zero Sugar Soft Drink... ✅ MATCH FOUND!
[36/172] Searching: Confetteria Raffaello Coconut and W... ✅ MATCH FOUND!
[37/172] Searching: Del Monte Green Apple Fruit Drink C... ✅ MATCH FOUND!
[38/172] Searching: Del Monte Penne Rigate Pasta Durum ... ✅ MATCH FOUND!
[39/172] Searching: Del Monte Sliced Black Olives... ✅ MATCH FOUND!
[40/172] Searching: Doritos Dinamita Fiery Lime & Chill... ✅ MATCH FOUND!
[41/172] Searching: Dr. Oetker FunFoods Pizza Topping A... ✅ MATCH FOUND!
[42/172] Searching: Dr. Oetker Funfoods Stripes - Mayo ... ✅ MATCH FOUND!
[43/172] Searching: Dr. Oetker Kuppies Chocolate Waffle... ✅ MATCH FOUND!
[44/172] Searching: Dr. Oetker Kuppies Strawberry Waffl... ✅ MATCH FOUND!
[45/172] Searching: Oetker FunFoods Pesto Italian Sauce... ✅ MATCH FOUND!
[46/172] Searching: Dr Pepper Sparkling Fruit Flavour S... ✅ MATCH FOUND!
[47/172] Searching: Fanta Orange Flavoured Soft Drink... ✅ MATCH FOUND!
[48/172] Searching: Ferrero Rocher... ✅ MATCH FOUND!
[49/172] Searching: Ferrero Rocher Moments Pack... ✅ MATCH FOUND!
[50/172] Searching: Galaxy Cookie Crumble CHOCOLATE BAR... ✅ MATCH FOUND!
[51/172] Searching: Galaxy Fusions Silky Smooth Dark CH... ✅ MATCH FOUND!
[52/172] Searching: Galaxy Smooth Milk CHOCOLATE BAR... ✅ MATCH FOUND!
[53/172] Searching: Gatorade Blue Bolt Zero Sugar Energ... ✅ MATCH FOUND!
[54/172] Searching: Gatorade Lemon Zero Sugar Energy Dr... ❌ Not Found
[55/172] Searching: Gatorade Orange Zero Sugar Energy D... ✅ MATCH FOUND!
[56/172] Searching: Godiva Dark Chocolate Blood Orange ... ❌ Not Found
[57/172] Searching: Godiva Milk Chocolate Rich & Creamy... ✅ MATCH FOUND!
[58/172] Searching: Godiva Salted Caramel Belgian Milk ... ✅ MATCH FOUND!
[59/172] Searching: Godiva Signature 72% Cacao Dark Cho... ❌ Not Found
[60/172] Searching: Haribo Goldbaren... ✅ MATCH FOUND!
[61/172] Searching: Hershey's Chocolate Milkshake... ✅ MATCH FOUND!
[62/172] Searching: Hershey's Cookies 'N' Creme CHOCOLA... ✅ MATCH FOUND!
[63/172] Searching: Hershey's Cookies and Cream Milksha... ✅ MATCH FOUND!
[64/172] Searching: Hershey's Creamy Milk CHOCOLATE BAR... ✅ MATCH FOUND!
[65/172] Searching: Hershey's Dark CHOCOLATE BAR... ✅ MATCH FOUND!
[66/172] Searching: Hershey's Exotic Dark Blueberry And... ❌ Not Found
[67/172] Searching: Hershey's Exotic Dark Chocolate Cal... ✅ MATCH FOUND!
[68/172] Searching: Hershey's Exotic Dark Pomegranate C... ✅ MATCH FOUND!
[69/172] Searching: Hershey's Exotic Raspberry & Goji D... ✅ MATCH FOUND!
[70/172] Searching: Hershey's Kisses Almonds Chocolate... ✅ MATCH FOUND!
[71/172] Searching: Hershey's Kisses Choco Truffle... ✅ MATCH FOUND!
[72/172] Searching: Hershey's Kisses Cookies 'N' Cream ... ✅ MATCH FOUND!
[73/172] Searching: Hershey's Kisses Hazelnut 'N' Cooki... ✅ MATCH FOUND!
[74/172] Searching: Hershey's Kisses Milk Chocolate... ✅ MATCH FOUND!
[75/172] Searching: Hershey's Strawberry Milkshake... ✅ MATCH FOUND!
[76/172] Searching: Hershey's Cocoa + Almond Spread... ✅ MATCH FOUND!
[77/172] Searching: Hershey's Cocoa Powder... ✅ MATCH FOUND!
[78/172] Searching: Horlicks Nutrition Drink Jar... ✅ MATCH FOUND!
[79/172] Searching: Horlicks Women's Plus Caramel Drink... ✅ MATCH FOUND!
[80/172] Searching: Kellogg's Chocolate Muesli... ✅ MATCH FOUND!
[81/172] Searching: Kellogg's Corn Flakes With Real Str... ✅ MATCH FOUND!
[82/172] Searching: Kellogg's Muesli Fruit Nut & Seeds ... ✅ MATCH FOUND!
[83/172] Searching: Kellogg's Multigrain Chocos... ✅ MATCH FOUND!
[84/172] Searching: Kinder Creamy Milky And Cocoa With ... ✅ MATCH FOUND!
[85/172] Searching: KOPIKO Cappuccino Coffee Candy... ✅ MATCH FOUND!
[86/172] Searching: Lay's American Cream & Onion Potato... ✅ MATCH FOUND!
[87/172] Searching: Lay's American Cream & Onion Potato... ✅ MATCH FOUND!
[88/172] Searching: Lay's Classic Salted Potato Chips... ✅ MATCH FOUND!
[89/172] Searching: Lay's India's Magic Masala Potato C... ✅ MATCH FOUND!
[90/172] Searching: Lay's India's Magic Masala Potato C... ✅ MATCH FOUND!
[91/172] Searching: Lay's Potato Chips - Sizzling Hot S... ✅ MATCH FOUND!
[92/172] Searching: Lay's Potato Chips WAFERstyle - Sal... ✅ MATCH FOUND!
[93/172] Searching: Lay's Spanish Tomato Tango Potato C... ✅ MATCH FOUND!
[94/172] Searching: Lay's WAFERChips Red Chilli... ❌ Not Found
[95/172] Searching: Lay's West Indies Hot 'n' Sweet Chi... ✅ MATCH FOUND!
[96/172] Searching: Limca Lemon Soft Drink... ✅ MATCH FOUND!
[97/172] Searching: Cocoa mass, sugar, cocoa butter, VA... ✅ MATCH FOUND!
[98/172] Searching: Lindt Excellence 70 % Cocoa Dark Ch... ✅ MATCH FOUND!
[99/172] Searching: Lindt Excellence 90% Cocoa Supreme ... ✅ MATCH FOUND!
[100/172] Searching: Lindt Excellence Orange Intense Dar... ✅ MATCH FOUND!
[101/172] Searching: Lindt Exotic Milk Cornet Chocolate... ✅ MATCH FOUND!
[102/172] Searching: Lindt Lindor Smooth Melting Assorte... ✅ MATCH FOUND!
[103/172] Searching: Lindt Swiss Classic Milk Chocolate... ✅ MATCH FOUND!
[104/172] Searching: Lotte Coffy Bite Classic... ✅ MATCH FOUND!
[105/172] Searching: Lotte Eclairs Coffy Bite Toffee... ✅ MATCH FOUND!
[106/172] Searching: MAGGI 2-Minute Instant Noodles... ✅ MATCH FOUND!
[107/172] Searching: Maggi Chicken Instant Noodles... ✅ MATCH FOUND!
[108/172] Searching: Maggi Chilly Chow Cuppa Noodles... ✅ MATCH FOUND!
[109/172] Searching: Maggi Korean BBQ Veg Instant Noodle... ✅ MATCH FOUND!
[110/172] Searching: Maggi Masala Cuppa Noodles... ✅ MATCH FOUND!
[111/172] Searching: Maggi Nutri-licious Masala Veg Atta... ✅ MATCH FOUND!
[112/172] Searching: Maggi Special Masala Instant Noodle... ✅ MATCH FOUND!
[113/172] Searching: Maltesers Chocolate... ✅ MATCH FOUND!
[114/172] Searching: Mars Caramel CHOCOLATE BAR... ✅ MATCH FOUND!
[115/172] Searching: McCain Mini Samosa - Cheese Corn... ❌ Not Found
[116/172] Searching: McCain Smile... ❌ Not Found
[117/172] Searching: Mcvitie's Digestive High Fibre Bisc... ✅ MATCH FOUND!
[118/172] Searching: Mentos Chewy Dragees... ✅ MATCH FOUND!
[119/172] Searching: Mentos Rainbow Assorted Flavour Che... ✅ MATCH FOUND!
[120/172] Searching: Mentos Strawberry Flavour Toffee... ✅ MATCH FOUND!
[121/172] Searching: Milka Raisins & Nuts Milk Chocolate... ✅ MATCH FOUND!
[122/172] Searching: Nestle Milo Health Chocolate Drink ... ✅ MATCH FOUND!
[123/172] Searching: Mirinda Orange Flavoured Soft Drink... ✅ MATCH FOUND!
[124/172] Searching: Mountain Dew Lemon Soft Drink... ✅ MATCH FOUND!
[125/172] Searching: BRU Classic Cold Coffee Tetra Pack... ✅ MATCH FOUND!
[126/172] Searching: Nescafe Cafe Style Iced Frappe Cold... ✅ MATCH FOUND!
[127/172] Searching: Nescafe Ready To Drink Coffee Flavo... ✅ MATCH FOUND!
[128/172] Searching: Nescafe Ready To Drink Coffee Flavo... ✅ MATCH FOUND!
[129/172] Searching: Kitkat Delights Hazelnut... ✅ MATCH FOUND!
[130/172] Searching: Nestle Cerelac Multigrain & Fruits ... ✅ MATCH FOUND!
[131/172] Searching: Nestle Cerelac Wheat Apple Carrot B... ✅ MATCH FOUND!
[132/172] Searching: Nestle KitKat Delights Caramel... ✅ MATCH FOUND!
[133/172] Searching: Nestle KitKat Delights Dark... ❌ Not Found
[134/172] Searching: Nestle KitKat Delights Rich... ✅ MATCH FOUND!
[135/172] Searching: Nestle Milkmaid Partly Skimmed Swee... ✅ MATCH FOUND!
[136/172] Searching: Nestle Munch Max Choco Coated Crunc... ✅ MATCH FOUND!
[137/172] Searching: Nutella Hazelnut Spread with Cocoa... ✅ MATCH FOUND!
[138/172] Searching: Orbit Sugar-Free Mixed Fruit Chewin... ❌ Not Found
[139/172] Searching: Cadbury Chocobakes ChocLayered Cake... ✅ MATCH FOUND!
[140/172] Searching: Cadbury Chocobakes ChocoChip Cookie... ✅ MATCH FOUND!
[141/172] Searching: Pillsbury Butterscotch Flavour Panc... ✅ MATCH FOUND!
[142/172] Searching: Pillsbury Chocolate Flavour Pancake... ✅ MATCH FOUND!
[143/172] Searching: Pillsbury VANILLA CAKE Custard Powd... ❌ Not Found
[144/172] Searching: Pringles Imported Potato Chips - Ra... ✅ MATCH FOUND!
[145/172] Searching: Pringles Imported Potato Crisps - B... ✅ MATCH FOUND!
[146/172] Searching: Pringles Potato Chips Desi Masala T... ✅ MATCH FOUND!
[147/172] Searching: Pringles Potato Chips Original Flav... ✅ MATCH FOUND!
[148/172] Searching: Pringles Potato Chips Original Flav... ✅ MATCH FOUND!
[149/172] Searching: Pringles Potato Chips Peri Peri Fla... ✅ MATCH FOUND!
[150/172] Searching: Pringles Potato Chips Pizza Flavour... ✅ MATCH FOUND!
[151/172] Searching: Pringles Potato Chips Tangy Tomato ... ✅ MATCH FOUND!
[152/172] Searching: Quaker Oats Breakfast Cereal... ✅ MATCH FOUND!
[153/172] Searching: Red Bull Energy Drink... ✅ MATCH FOUND!
[154/172] Searching: Skittles Original Bite-Size Fruit C... ✅ MATCH FOUND!
[155/172] Searching: Skittles Wildberry Bite-Size Fruit ... ❌ Not Found
[156/172] Searching: Snickers Almond Filled CHOCOLATE BA... ✅ MATCH FOUND!
[157/172] Searching: Snickers Filled with Brownie, Peanu... ❌ Not Found
[158/172] Searching: Snickers Peanut Filled CHOCOLATE BA... ❌ Not Found
[159/172] Searching: Sprite Lemon and Lime Soft Drink... ✅ MATCH FOUND!
[160/172] Searching: Tabasco Red Pepper Sauce... ✅ MATCH FOUND!
[161/172] Searching: Thums Up X Force... ✅ MATCH FOUND!
[162/172] Searching: Tic Tac Candy - Red Apple Treat... ✅ MATCH FOUND!
[163/172] Searching: Tic Tac Orange Hard Candy... ✅ MATCH FOUND!
[164/172] Searching: Tic Tac Seeds Fennel (Saunf)... ✅ MATCH FOUND!
[165/172] Searching: Tic Tac Seeds Jeera Blacksalt... ❌ Not Found
[166/172] Searching: Toblerone Black Chocolate... ✅ MATCH FOUND!
[167/172] Searching: Toblerone Fruit & Nut Chocolate... ✅ MATCH FOUND!
[168/172] Searching: Tropicana Delight Cranberry Fruit J... ❌ Not Found
[169/172] Searching: Tropicana Delight Guava Fruit Juice... ✅ MATCH FOUND!
[170/172] Searching: Tropicana Delight Mixed Fruit Juice... ✅ MATCH FOUND!
[171/172] Searching: Twix Minis Cookie Caramel Chocolate... ✅ MATCH FOUND!
[172/172] Searching: Wedel Milk CHOCOLATE BAR... ✅ MATCH FOUND!

==================================================
🎉 BATCH LOOKUP COMPLETE!
Successfully Matched: 151 / 172 products (87.8%)
==================================================

💾 Enriched datasets saved to data/multinational_brand_enriched.csv and data/benchmark_candidates.json!

In [63]:
# Cell 7: Manual Visual Verification - See Indian vs International Ingredients Side-by-Side

import pandas as pd
pd.set_option('display.max_colwidth', 120)   # Show full ingredient text

matched_df = df[df['OFF_UK_Match_Found_Y_N'] == 'Yes'].reset_index(drop=True)

print(f"✅ Total Products Ready for Visual Inspection: {len(matched_df)}\n")
print("=" * 80)

# Print each product in a clean readable format
for i, row in matched_df.iterrows():
    print(f"\n🔢 Product #{i+1}")
    print(f"   📦 Brand      : {row['Brand_Name']}")
    print(f"   🏷️  Item       : {row['Item name']}")
    print(f"   🇮🇳 Indian ING : {str(row['Ingredients'])[:200]}...")
    print(f"   🌍 Global ING : {str(row['OFF_UK_Ingredients'])[:200]}...")
    print(f"   🔖 Barcode    : {row['OFF_UK_Barcode']}")
    print("-" * 80)
    
    # Pause every 10 products so you can read comfortably
    if (i + 1) % 10 == 0:
        print(f"\n... Showing {i+1}/{len(matched_df)} products so far ...\n")

✅ Total Products Ready for Visual Inspection: 151

================================================================================

🔢 Product #1
   📦 Brand      : 7 UP
   🏷️  Item       : 7 Up Lemon Soft Drink
   🇮🇳 Indian ING : Carbonated Water, Sugar, Acidity Regulators (330,Acidity Regulators 331,Acidity Regulators 296), Preservative (211)...
   🌍 Global ING : carbonated water, sugar, acids (citric acid, malic acid), natural lemon and lime flavouring with other natural flavourings, acidity regulator (sodium citrate), sweetner (steviol glycosides),...
   🔖 Barcode    : 4060800304360
--------------------------------------------------------------------------------

🔢 Product #2
   📦 Brand      : 7 UP NIMBOOZ
   🏷️  Item       : 7UP Nimbooz Soft Drink
   🇮🇳 Indian ING : Water, Sugar, Concentrated Lemon Juice (0.7%), Acidity Regulators 331(Iii),Acidity Regulators 296,Acidity Regulators 330, Flavour (Natural Flavouring Substances), Iodised Salt, Stabilizer (445(Iii)), ...
   🌍 Global ING : WATER, SUGAR, CONCENTRATED LEMON JUICE (0.7%). ACIDITY REGULATORS (331), 296,330), FLAVOUR (NATURAL FLAVOURING SUBSTANCES), IODISED SALT, STABILIZER (445), PRESERVATIVE (202). EQUIVALENT TO 5% LEON JU...
   🔖 Barcode    : 8902080334179
--------------------------------------------------------------------------------

🔢 Product #3
   📦 Brand      : BETTY CROCKER
   🏷️  Item       : Betty Crocker Triple Chocolate Brownie Instant Cake Mix Powder
   🇮🇳 Indian ING : Sugar, Refined Wheat Flour (Maida), Cocoa Powder (6.35%), Dark Compound Choco Chips (6.0%) (Sugar, Cocoa Solids, Hydrogenated Vegetable Oil (Palm), Dextrose, Emulsifier (Ins492, Ins322)), White Compou...
   🌍 Global ING : Enriched Flour Bleached, Sugar, Cocoa Processed with Alkali, Corn Syrup, Chocolate Chips (sugar, chocolate liquor, cocoa butter, soy lecithin, natural flavor), Leavening (baking soda, monocalcium phos...
   🔖 Barcode    : 0016000207769
--------------------------------------------------------------------------------

🔢 Product #4
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Bournville Cranberry 50% Dark CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Cocoa Butter (24%), Cocoa Solids (18%), Dried Sweetened Cranberries (11%) (Cranberries, Sugar), Almonds (7%), Milk Solids, Emulsifiers (442, 476), Flavours (Natural and Nature Identical Flavour...
   🌍 Global ING : Sugar, cocoa powder, acidity regulator (potassium carbonates), flavouring....
   🔖 Barcode    : 5034660021582
--------------------------------------------------------------------------------

🔢 Product #5
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Bournville Fruit & Nut 50% Dark CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Cocoa Butter (24%), Cocoa Solids (18%), Raisins (75%), Cashew Nuts (4%), Apricot Kernels (4%), Milk Solids, Emulsifiers (442, 476), Nature Identical Flavoring Substance...
   🌍 Global ING : Sugar, cocoa mass, raisins, palm oil, cocoa butter, emulsifiers (SOYA lecithins, E476), flavouring, skimmed MILK powder...
   🔖 Barcode    : 7622210696366
--------------------------------------------------------------------------------

🔢 Product #6
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Bournville Rich Cocoa 70% Dark CHOCOLATE BAR
   🇮🇳 Indian ING : Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Milk Solids, Nature Identical Flavouring Substances, and Sugar...
   🌍 Global ING : sugar, cocoa butter, cocoa mass, palm oil, emulsifiers (soya lecithin, e476),skimmed milk powder...
   🔖 Barcode    : 7622210249661
--------------------------------------------------------------------------------

🔢 Product #7
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Temptations Almond Treat Premium CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Almonds (17%), Cocoa Butter, Milk Solids, Cocoa Solids, Fractionated Fat, Emulsifiers (442,476), Flavours (Natural, Nature Identical And Artificial (VANILLA CAKE) Flavouring Substances). Contai...
   🌍 Global ING : Sugar, cocoa powder, acidity regulator (potassium carbonates), flavouring....
   🔖 Barcode    : 5034660021582
--------------------------------------------------------------------------------

🔢 Product #8
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Temptations Rum & Raisins Premium CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Raisins (18%), Cocoa Butter, Cocoa Solids, Milk Solids, Fractionated Fat, Emulsifiers (442, 476), Flavours (Natural, Nature Identical, and Artificial (Rum, Raisin, VANILLA CAKE) Flavouring Subs...
   🌍 Global ING : Sugar, Cocoa Butter, Raisins (18%*), Cocoa Solids, Milk Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical and Artificial (Rum, Raisin, Vanilla) Flavouring Substances). Allergen Infor...
   🔖 Barcode    : 7622201138394
--------------------------------------------------------------------------------

🔢 Product #9
   📦 Brand      : CADBURY
   🏷️  Item       : Bournvita Chocolate
   🇮🇳 Indian ING : Cereal Extract 56% (Barley, Millets, Wheat), Sugar, Cocoa Solids, Maltodextrin, Colour (150C), Minerals, Wheat Gluten, Liquid Glucose, Emulsifiers (322, 471), Milk Solids, Vitamins, Raising Agent (500...
   🌍 Global ING : Cereal Extract 56%*(Barley, Millets, Wheat), Sugar, Cocoa Solids, Maltodextrin, Colour (150c), Minerals, Wheat Gluten, Liquid Glucose, Emulsifiers (322,471), Milk Solids, Vitamins, Raising Agent (500(...
   🔖 Barcode    : 7622202026683
--------------------------------------------------------------------------------

🔢 Product #10
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury 5 Star 3D CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Liquid Glucose, Milk Solids (14%), Hydrogenated Vegetable Fat, Cocoa Solids (6%), Rice Crispies (2.8%), Cocoa Butter, Edible Salt, Hydrolysed Vegetable Protein [1, 4, 5, 8]. Centre filling 67%*...
   🌍 Global ING : Sugar, cocoa powder, acidity regulator (potassium carbonates), flavouring....
   🔖 Barcode    : 5034660021582
--------------------------------------------------------------------------------

... Showing 10/151 products so far ...


🔢 Product #11
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury 5 Star CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar Boiled Confectionery. Ingredients: Sugar, Liquid Glucose, Milk Solids, Invert Sugar, Hydrogenated Oil, Cocoa Solids, Cocoa Butter, Fractionated Fat, Emulsifiers (442, 471, 476), Hydrolyzed Veget...
   🌍 Global ING : Sugar, Liquid Glucose, Invert Sugar, Milk Solids, Hydrogenated Oil, Cocoa Butter, Cocoa Solids, Fractionated Fat, Lactose-rich Deproteinized Whey Permeate Powder, Emulsifiers (442, 471, 476), Hydrolyz...
   🔖 Barcode    : 7622201150419
--------------------------------------------------------------------------------

🔢 Product #12
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Bournville Rich Cocoa 50% Dark CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Cocoa Butter (29%), Cocoa Solids (22%), Milk Solids, Emulsifiers (442, 476), Nature Identical Flavoring Substances...
   🌍 Global ING : Sugar, cocoa powder, acidity regulator (potassium carbonates), flavouring....
   🔖 Barcode    : 5034660021582
--------------------------------------------------------------------------------

🔢 Product #13
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Bites Hazelnut Chocolate Pack
   🇮🇳 Indian ING : Milk Chocolate (Sugar, Milk Solids, Cocoa Butter, Cocoa Solids, Fractionated Fat, Emulsifiers (442, 476), Natural Flavours, Nature Identical and Artificial VANILLA CAKE Flavouring), Hazelnuts, Glazing...
   🌍 Global ING : milk, sugar, cocoa butter, cocoa mass, vegetable fats (palm, shea), emulsifiers (e442, e476), flavourings may contain nuts, wheat, ,quot,the equivalent of 426 ml of fresh liquid milk in every 227 g of...
   🔖 Barcode    : 7622201148782
--------------------------------------------------------------------------------

🔢 Product #14
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Chocolate Bar
   🇮🇳 Indian ING : Sugar, Milk Solids (23%), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical, and Artificial VANILLA CAKE)...
   🌍 Global ING : milk, sugar, cocoa butter, cocoa mass, vegetable fats (palm, shea), emulsifiers (e442, e476), flavourings may contain nuts, wheat, ,quot,the equivalent of 426 ml of fresh liquid milk in every 227 g of...
   🔖 Barcode    : 7622201148782
--------------------------------------------------------------------------------

🔢 Product #15
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Crispello CHOCOLATE BAR
   🇮🇳 Indian ING : Milk Chocolate 50%- Sugar, Milk Solids (11%), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical and Artificial (VANILLA CAKE) Flavouring Substances), Centre 50%- ...
   🌍 Global ING : Milk Chocolate (64%): Sugar, Milk Solids (12%), Cocoa Butter, Coco Solids, Fractionated Fat, Emulsifiers (42,476), Favours (Natural Nature Mentical and Artificial (Caramel and Vanilla) Flavouring Subs...
   🔖 Barcode    : 7622202819445
--------------------------------------------------------------------------------

🔢 Product #16
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Fruit & Nut CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Milk Solids (18%), Cocoa Butter, Dry Fruit (Raisins (10%)), Cocoa Solids, Almonds (9%), Fractionated Fat, Emulsifiers (442, 476), Flavours (Natural, Nature Identical and Artificial (VANILLA CAK...
   🌍 Global ING : milk, sugar, dried grapes, cocoa butter, almonds, cocoa mass, vegetable fats (palm, shea), emulsifiers (e442, e476), flavourings...
   🔖 Barcode    : 7622201149611
--------------------------------------------------------------------------------

🔢 Product #17
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Lickables Chocolate with Oreo Chunks
   🇮🇳 Indian ING : Sugar, Palm Superolein, Milk Solids (11%), Biscuit 10% (Refined Wheat Flour (Maida), Sugar, Palmolein, Invert Sugar, Cocoa Solids, Leavening Agents (500)(i), 503(i), lodised Salt, Emulsifier (322), Fl...
   🌍 Global ING : milk, sugar, cocoa butter, cocoa mass, vegetable fats (palm, shea), emulsifiers (e442, e476), flavourings may contain nuts, wheat, ,quot,the equivalent of 426 ml of fresh liquid milk in every 227 g of...
   🔖 Barcode    : 7622201148782
--------------------------------------------------------------------------------

🔢 Product #18
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Silk Bubbly CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Milk Solids (25%), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical, and Artificial (VANILLA CAKE) Flavouring Substances)...
   🌍 Global ING : Sugar, Milk Solids (25%), Cocoa Butter, Cocoa Solids, Emulsifiers (4,470) Flavours (Natural, Nature Identical and Artificial (Vanilla) Flavouring Substances) Allergen Information: Contains Milk. May C...
   🔖 Barcode    : 7622202290633
--------------------------------------------------------------------------------

🔢 Product #19
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Silk CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Milk Solids, Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Natural Flavours, Nature Identical and Artificial VANILLA CAKE Flavouring Substances...
   🌍 Global ING : Sugar, Milk solids(25%*), Cocoa butter, Cocoa solids, Emulisifiers(442,476), Flavours(natural, nature, identical, and artificial (vanilla) flavouring substances)...
   🔖 Barcode    : 7622202271861
--------------------------------------------------------------------------------

🔢 Product #20
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Silk Desserts Plum Cake CHOCOLATE BAR
   🇮🇳 Indian ING : Milk Chocolate (60%)- Sugar, Mik Solids (15%) Cocoa Butter Cocoa Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical and Artificial (VANILLA CAKE) Flavouring Substances); Centre (40%)-...
   🌍 Global ING : Sugar, Milk solids(25%*), Cocoa butter, Cocoa solids, Emulisifiers(442,476), Flavours(natural, nature, identical, and artificial (vanilla) flavouring substances)...
   🔖 Barcode    : 7622202271861
--------------------------------------------------------------------------------

... Showing 20/151 products so far ...


🔢 Product #21
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Silk Hazelnut CHOCOLATE BAR
   🇮🇳 Indian ING : Sugar, Milk Solids (21%), Hazelnuts (16%), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical, and Artificial VANILLA CAKE)...
   🌍 Global ING : Sugar, Milk solids(25%*), Cocoa butter, Cocoa solids, Emulisifiers(442,476), Flavours(natural, nature, identical, and artificial (vanilla) flavouring substances)...
   🔖 Barcode    : 7622202271861
--------------------------------------------------------------------------------

🔢 Product #22
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Dairy Milk Silk Mousse CHOCOLATE BAR
   🇮🇳 Indian ING : Milk Chocolate 55%- Sugar, Milk Solids (13%), Cocoa Butter, Cocoa Solids, Emulsifiers (442, 476), Flavours (Natural, Nature Identical and Artificial (VANILLA CAKE) Flavouring Substances) Centre Fillin...
   🌍 Global ING : milk, sugar, cocoa butter, cocoa mass, vegetable fats (palm, shea), emulsifiers (e442, e476), flavourings may contain nuts, wheat, ,quot,the equivalent of 426 ml of fresh liquid milk in every 227 g of...
   🔖 Barcode    : 7622201148782
--------------------------------------------------------------------------------

🔢 Product #23
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Fuse Mini Treats Chocolate Pack
   🇮🇳 Indian ING : Centre Filling 72%- Peanuts (19%), Sugar, Interesterified Vegetable Fat, Liquid Glucose, Milk Solids,Hydrogenated Vegetable Oil, Cocoa Solids, Invert Sugar. Humectant (422), Iodised Salt, Emulsifiers ...
   🌍 Global ING : Sugar, cocoa powder, acidity regulator (potassium carbonates), flavouring....
   🔖 Barcode    : 5034660021582
--------------------------------------------------------------------------------

🔢 Product #24
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Gems Chocolate Mini Treats Pack
   🇮🇳 Indian ING : Cocoa Solids (8%), Colours (102, 110, 122, 124, 127, 132, 133, and 171), Emulsifiers (414, 442, and 476), Flavours Natural, Nature Identical, and Artificial (Caramel and VANILLA CAKE) Flavouring Subst...
   🌍 Global ING : Sugar, Hydrogenated Oils, Milk Solids, Cocoa Solids (8%*), Refined Wheat Flour (Maida), Emulsifiers (414, 442, 476), Colours (171, 102, 133, 124, 127, 122, 132, 110), Glazing Agent (903), Liquid Gluco...
   🔖 Barcode    : 7622202216695
--------------------------------------------------------------------------------

🔢 Product #25
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Gems Surprise Ball Chocolate
   🇮🇳 Indian ING : Sugar, Hydrogenated Oils, Milk Solids, Cocoa Solids (8%*), Refined Wheat Flour (Maida), Emulsifiers (414, 442, 476), Colours (171, 102, 133, 124, 127, 122, 132, 110), Glazing Agent (903), Liquid Gluco...
   🌍 Global ING : Sugar, Hydrogenated Oils, Milk Solids, Cocoa Solids (8%*), Refined Wheat Flour (Maida), Emulsifiers (414, 442, 476), Colours (171, 102, 133, 124, 127, 122, 132, 110), Glazing Agent (903), Liquid Gluco...
   🔖 Barcode    : 7622202216695
--------------------------------------------------------------------------------

🔢 Product #26
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Nutties Chocolate
   🇮🇳 Indian ING : Center (56%) (Sugar, Cashews (11%), Milk Solids, Glazing Agent (904), Stabilizers (1400, 414), lodised Salt, Flavours (Natural and Nature Identical Flavouring Substances), Emulsifier (442), Almond); M...
   🌍 Global ING : Center (55%*) (Sugar, Cashew Nuts (11%), Milk Solids, lodised Salt, Flavour (Natural and Nature Identical Flavouring Substances), Emulsifier (442), Almonds), Milk Chocolate (44%) (Sugar, Milk A Solids...
   🔖 Barcode    : 7622202031618
--------------------------------------------------------------------------------

🔢 Product #27
   📦 Brand      : CADBURY
   🏷️  Item       : Cadbury Oreo Original Chocolatey Sandwich Biscuits
   🇮🇳 Indian ING : Refined Wheat Flour (Maida), Sugar, Fractionated Fat, Palmolein, Invert Sugar, Cocoa Solids (2%*), Leavening Agents [500(ii), 503(ii)], Starch, lodised Salt, Emulsifier (322), Nature Identical Flavour...
   🌍 Global ING : milk**, sugar, vegetable fats (palm, shea), cocoa butter, wheat flour, whey powder (from milk), skimmed milk powder, cocoa mass, milk fat, reduced fat cocoa powder, emulsifiers (e442, soya lecithin, e...
   🔖 Barcode    : 7622300754136
--------------------------------------------------------------------------------

🔢 Product #28
   📦 Brand      : CHEETOS
   🏷️  Item       : Cheetos Masala PUFFS, Crispy Chips & Snacks
   🇮🇳 Indian ING : Corn meal, Rice meal, Edible Vegetable Oil (Palmolein), Gram meal, Seasoning (Spices and Condiments, Iodised Salt, Black salt, Flavour, Maltodextrin, Tomato powder, Sugar, Acidity Regulator), Wheat fi...
   🌍 Global ING : ENRICHED CORN MEAL (CORN MEAL, FERROUS SULFATE, NIACIN, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID), VEGETABLE OIL (CORN OIL, CANOLA OIL, SUNFLOWER OIL), WHEY, CHEDDAR CHEESE (MILK, CHEESE CULTURES, ...
   🔖 Barcode    : 0028400040112
--------------------------------------------------------------------------------

🔢 Product #29
   📦 Brand      : COKE ZERO
   🏷️  Item       : Coca-Cola Zero Sugar Soft Drink
   🇮🇳 Indian ING : Carbonated water, acidity regulators 338, acidity regulators 331(iii), sweeteners 955, sweeteners 950, preservative (211), caffeine (9.2 mg/100g), colour (150d), flavours (natural flavoring substances...
   🌍 Global ING : carbonated water, colour (e150d), acid (phosphoric acid) sweeteners (aspartame, acesulfame-k enzymatically produced steviol glycosides), natural flavourings, caffeine flavouring, acidity regulator (so...
   🔖 Barcode    : 5449000131805
--------------------------------------------------------------------------------

🔢 Product #30
   📦 Brand      : CONFETTERIA RAFFAELLO
   🏷️  Item       : Confetteria Raffaello Coconut and White Almond
   🇮🇳 Indian ING : Desiccated Coconut, Palm Oil, Sugar, Almond, Skimmed Milk Powder, Whey Powder, Shea Butter, Refined Wheat Flour (Maida), Tapioca Starch, Nature Identical Flavouring Substances, Emulsifier (Lecithin - ...
   🌍 Global ING : vegetable fats (palm, shea), shredded coconut 23,5%, sugar, almond 8%, skimmed milk powder, lactoserum powder, wheat flour, flavours, emulsifiers: lecithins [soy], uptake powder: sodium acid carbonate...
   🔖 Barcode    : 5413548040592
--------------------------------------------------------------------------------

... Showing 30/151 products so far ...


🔢 Product #31
   📦 Brand      : DEL MONTE
   🏷️  Item       : Del Monte Green Apple Fruit Drink Crisp
   🇮🇳 Indian ING : Acidity Regulators (INS 296, INS 330), Apple Juice (Reconstituted From Apple Juice Concentrate) (30%), Iodized Salt, Sugar, Water...
   🌍 Global ING : concentrated orange juice (82.5%), concentrated grape juice (9.5%), concentrated apple juice (8%)....
   🔖 Barcode    : 5010693601960
--------------------------------------------------------------------------------

🔢 Product #32
   📦 Brand      : DEL MONTE
   🏷️  Item       : Del Monte Penne Rigate Pasta Durum Wheat
   🇮🇳 Indian ING : Durum Wheat Semolina...
   🌍 Global ING : PEACHES, CLARIFIED GRAPE JUICE FROM CONCENTRATE, ACIDITY REGULATOR: CITRIC ACID....
   🔖 Barcode    : 0024000124955
--------------------------------------------------------------------------------

🔢 Product #33
   📦 Brand      : DEL MONTE
   🏷️  Item       : Del Monte Sliced Black Olives
   🇮🇳 Indian ING : Olives (48.5%), Water, Iodized Salt, Color Retention Agent (Ins 579)...
   🌍 Global ING : PEACHES, CLARIFIED GRAPE JUICE FROM CONCENTRATE, ACIDITY REGULATOR: CITRIC ACID....
   🔖 Barcode    : 0024000124955
--------------------------------------------------------------------------------

🔢 Product #34
   📦 Brand      : DORITOS