# Phase 1: Data Cleaning & Normalization Notebook

Welcome! In this notebook, we will interactively load, inspect, clean brand typos, and export the cleaned dataset step-by-step using **Pandas**.

## Cell 1: Import Libraries & Configure File Paths

In [17]:
import os
import pandas as pd
from pathlib import Path

# Define project data directory paths
DATA_DIR = Path("data")
INPUT_CSV = DATA_DIR / "multinational_brand_shortlist.csv"
OUTPUT_CSV = DATA_DIR / "multinational_brand_cleaned.csv"

print(f"Input CSV Path: {INPUT_CSV.resolve()}")

Input CSV Path: C:\Users\ARYAN PRAJAPATI\OneDrive\Desktop\python\ingredient_platform\data\multinational_brand_shortlist.csv

## Cell 2: Load the Raw Dataset & Inspect

In [18]:
# Load raw CSV file into a Pandas DataFrame
df = pd.read_csv(INPUT_CSV)

print("=== Dataset Overview ===")
print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns\n")
df.head(10)

=== Dataset Overview ===
Shape: 172 rows, 15 columns

,Priority_Rank,S.No,Item name,Brand_Name,Category,Sub_Category,Ingredients,Serving_Size_g,Sugar_g,Total_Fat_g,OFF_UK_Barcode,OFF_UK_Match_Found_Y_N,Indian_Label_Verified_Y_N,Verification_Source_URL,Notes
0,1,184,7 Up Lemon Soft Drink,7 UP,JUICE,SODA,"Carbonated Water, Sugar, Acidity Regulators (3...",100.0,11.7,0,NaN,NaN,NaN,NaN,NaN
1,2,185,7UP Nimbooz Soft Drink,7 UP NIMBOOZ,JUICE,SODA,"Water, Sugar, Concentrated Lemon Juice (0.7%),...",100.0,10.6,0,NaN,NaN,NaN,NaN,NaN
2,3,705,Betty Crocker Triple Chocolate Brownie Instant...,BETTY CROCKER,INSTANT FOOD,CAKE MIX,"Sugar, Refined Wheat Flour (Maida), Cocoa Powd...",100.0,54.3,4.6,NaN,NaN,NaN,NaN,NaN
3,4,593,Bournvita Biscuits,BOUENVITA,BISCUIT,BISCUIT,"Refined Wheat Flour (Maida) (56%), Sugar, Palm...",100.0,28.3,15.3,NaN,NaN,NaN,NaN,NaN
4,5,391,Bounty Miniatures Coconut Filled Chocolate Pack,BOUNTY,CHOCOLATE,CHOCOLATE BAR,"Milk chocolate coating (44%) (Sugar, Milk soli...",100.0,50,25.8,NaN,NaN,NaN,NaN,NaN
5,6,401,Cadbury Bournville Cranberry 50% Dark CHOCOLAT...,BOURNVILLE,CHOCOLATE,CHOCOLATE BAR,"Sugar, Cocoa Butter (24%), Cocoa Solids (18%),...",100.0,45.7,31.6,NaN,NaN,NaN,NaN,NaN
6,7,402,Cadbury Bournville Fruit & Nut 50% Dark CHOCOL...,BOURNVILLE,CHOCOLATE,CHOCOLATE BAR,"Sugar, Cocoa Butter (24%), Cocoa Solids (18%),...",100.0,44.2,32.8,NaN,NaN,NaN,NaN,NaN
7,8,400,Cadbury Bournville Rich Cocoa 70% Dark CHOCOLA...,BOURNVILLE,CHOCOLATE,CHOCOLATE BAR,"Cocoa Butter, Cocoa Solids, Emulsifiers (442, ...",100.0,20.4,47.4,NaN,NaN,NaN,NaN,NaN
8,9,386,Cadbury Temptations Almond Treat Premium CHOCO...,BOURNVILLE,CHOCOLATE,CHOCOLATE BAR,"Sugar, Almonds (17%), Cocoa Butter, Milk Solid...",100.0,45.2,35,NaN,NaN,NaN,NaN,NaN
9,10,389,Cadbury Temptations Rum & Raisins Premium CHOC...,BOURNVILLE,CHOCOLATE,CHOCOLATE,"Sugar, Raisins (18%), Cocoa Butter, Cocoa Soli...",100.0,57,26,NaN,NaN,NaN,NaN,NaN

In [19]:
df

,Priority_Rank,S.No,Item name,Brand_Name,Category,Sub_Category,Ingredients,Serving_Size_g,Sugar_g,Total_Fat_g,OFF_UK_Barcode,OFF_UK_Match_Found_Y_N,Indian_Label_Verified_Y_N,Verification_Source_URL,Notes
0,1,184,7 Up Lemon Soft Drink,7 UP,JUICE,SODA,"Carbonated Water, Sugar, Acidity Regulators (3...",100.0,11.7,0,NaN,NaN,NaN,NaN,NaN
1,2,185,7UP Nimbooz Soft Drink,7 UP NIMBOOZ,JUICE,SODA,"Water, Sugar, Concentrated Lemon Juice (0.7%),...",100.0,10.6,0,NaN,NaN,NaN,NaN,NaN
2,3,705,Betty Crocker Triple Chocolate Brownie Instant...,BETTY CROCKER,INSTANT FOOD,CAKE MIX,"Sugar, Refined Wheat Flour (Maida), Cocoa Powd...",100.0,54.3,4.6,NaN,NaN,NaN,NaN,NaN
3,4,593,Bournvita Biscuits,BOUENVITA,BISCUIT,BISCUIT,"Refined Wheat Flour (Maida) (56%), Sugar, Palm...",100.0,28.3,15.3,NaN,NaN,NaN,NaN,NaN
4,5,391,Bounty Miniatures Coconut Filled Chocolate Pack,BOUNTY,CHOCOLATE,CHOCOLATE BAR,"Milk chocolate coating (44%) (Sugar, Milk soli...",100.0,50,25.8,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,168,142,Tropicana Delight Cranberry Fruit Juice,TROPICANA,JUICE,FRUIT BEVERAGE,"Water, Sugar, Concentrated Cranberry Juice (1....",100.0,10.5,0,NaN,NaN,NaN,NaN,NaN
168,169,131,Tropicana Delight Guava Fruit Juice,TROPICANA,JUICE,FRUIT BEVERAGE,"Water, Guava Pulp (22%), Sugar, Acidity Regula...",100.0,13.5,0,NaN,NaN,NaN,NaN,NaN
169,170,132,Tropicana Delight Mixed Fruit Juice,TROPICANA,JUICE,FRUIT BEVERAGE,"Water, Sugar, Concentrated Mixed Fruit Juice (...",100.0,10.2,0,NaN,NaN,NaN,NaN,NaN
170,171,366,Twix Minis Cookie Caramel Chocolate Pack,TWIX,CHOCOLATE,CHOCOLATE BAR,"Sugar, Liquid Glucose, Refined Wheat Flour (Ma...",100.0,48,23.7,NaN,NaN,NaN,NaN,NaN
171,172,446,Wedel Milk CHOCOLATE BAR,WEDEL,CHOCOLATE,CHOCOLATE BAR,"Sugar, Cocoa Butter, Dried Whole Milk, Cocoa M...",100.0,57,30,NaN,NaN,NaN,NaN,NaN

In [23]:
print(df.columns)

Index(['Priority_Rank', 'S.No', 'Item name', 'Brand_Name', 'Category',
       'Sub_Category', 'Ingredients', 'Serving_Size_g', 'Sugar_g',
       'Total_Fat_g', 'OFF_UK_Barcode', 'OFF_UK_Match_Found_Y_N',
       'Indian_Label_Verified_Y_N', 'Verification_Source_URL', 'Notes'],
      dtype='str')

In [25]:
df['Brand_Name'].unique()

<ArrowStringArray>
[                 '7 UP',          '7 UP NIMBOOZ',         'BETTY CROCKER',
             'BOUENVITA',                'BOUNTY',            'BOURNVILLE',
      'CADBERY BORNVITA',               'CADBURY',               'CHEETOS',
             'COKE ZERO', 'CONFETTERIA RAFFAELLO',             'DEL MONTE',
               'DORITOS',   'DR OETKERS FUNFOODS',             'DR PEPPER',
                 'FANTA',        'FERRERO ROCHER',                'GALAXY',
              'GATORADE',                'GODIVA',                'HARIBO',
              'HERSHEYS',             'HERSHYEYS',              'HORLICKS',
              'KELLOGGS',            'KINDER JOY',                'KOPIKO',
                 'LAY'S',                 'LIMCA',                 'LINDT',
                 'LOTTE',                 'MAGGI',             'MALTESERS',
                  'MARS',                'MCCAIN',              'MCVITIES',
                'MENTOS',                 'MILKA',                  'MILO',
               'MIRINDA',          'MOUMTAIN DEW',               'NESCAFE',
                'NESTLE',               'NUTELLA',                 'ORBIT',
                  'OREO',             'PILLSBURY',              'PRINGLES',
                'QUAKER',              'RED BULL',              'SKITTLES',
              'SNICKERS',                'SPRITE',               'TABASCO',
              'THUMS UP',               'TIC TAC',             'TOBLERONE',
             'TROPICANA',                  'TWIX',                 'WEDEL']
Length: 60, dtype: str

In [29]:
# Loop through the array and print each item on a new line
for item in df['Item name'].unique():
    print(item)

7 Up Lemon Soft Drink
7UP Nimbooz Soft Drink
Betty Crocker Triple Chocolate Brownie Instant Cake Mix Powder
Bournvita Biscuits
Bounty Miniatures Coconut Filled Chocolate Pack
Cadbury Bournville Cranberry 50% Dark CHOCOLATE BAR
Cadbury Bournville Fruit & Nut 50% Dark CHOCOLATE BAR
Cadbury Bournville Rich Cocoa 70% Dark CHOCOLATE BAR
Cadbury Temptations Almond Treat Premium CHOCOLATE BAR
Cadbury Temptations Rum & Raisins Premium CHOCOLATE BAR
Bournvita Chocolate
Cadbury 5 Star 3D CHOCOLATE BAR
Cadbury 5 Star CHOCOLATE BAR
Cadbury Bournville Rich Cocoa 50% Dark CHOCOLATE BAR
Cadbury Choclairs Gold Candy
Cadbury Dairy Milk Bites Hazelnut Chocolate Pack
Cadbury Dairy Milk Chocolate Bar
Cadbury Dairy Milk Crispello CHOCOLATE BAR
Cadbury Dairy Milk Fruit & Nut CHOCOLATE BAR
Cadbury Dairy Milk Lickables Chocolate with Oreo Chunks
Cadbury Dairy Milk Silk Bubbly CHOCOLATE BAR
Cadbury Dairy Milk Silk CHOCOLATE BAR
Cadbury Dairy Milk Silk Desserts Brownie CHOCOLATE BAR
Cadbury Dairy Milk Silk Desserts Plum Cake CHOCOLATE BAR
Cadbury Dairy Milk Silk Hazelnut CHOCOLATE BAR
Cadbury Dairy Milk Silk Mousse CHOCOLATE BAR
Cadbury Dairy Milk Silk Oreo CHOCOLATE BAR
Cadbury Fuse Mini Treats Chocolate Pack
Cadbury Gems Chocolate Mini Treats Pack
Cadbury Gems Surprise Ball Chocolate
Cadbury Nutties Chocolate
Cadbury Oreo Original Chocolatey Sandwich Biscuits
Cadbury Perk Mini Treats Chocolate coated Wafers
Cheetos Masala PUFFS, Crispy Chips & Snacks
Coca-Cola Zero Sugar Soft Drink
Confetteria Raffaello Coconut and White Almond
Del Monte Green Apple Fruit Drink Crisp
Del Monte Penne Rigate Pasta Durum Wheat
Del Monte Sliced Black Olives
Doritos Dinamita Fiery Lime & Chilli Flavour Namkeen
Dr. Oetker FunFoods Pizza Topping All-in-One Sauce
Dr. Oetker Funfoods Stripes - Mayo & Ketchup
Dr. Oetker Kuppies Chocolate Waffle
Dr. Oetker Kuppies Strawberry Waffle
Oetker FunFoods Pesto Italian Sauce
Dr Pepper Sparkling Fruit Flavour Soft Drink
Fanta Orange Flavoured Soft Drink
Ferrero Rocher
Ferrero Rocher Moments Pack
Galaxy Cookie Crumble CHOCOLATE BAR
Galaxy Fusions Silky Smooth Dark CHOCOLATE BAR, Made with 70% Cocoa
Galaxy Smooth Milk CHOCOLATE BAR
Gatorade Blue Bolt Zero Sugar Energy Drink
Gatorade Lemon Zero Sugar Energy Drink
Gatorade Orange Zero Sugar Energy Drink
Godiva Dark Chocolate Blood Orange Tablet Bar
Godiva Milk Chocolate Rich & Creamy
Godiva Salted Caramel Belgian Milk Chocolate
Godiva Signature 72% Cacao Dark Chocolate
Haribo Goldbaren
Hershey's Chocolate Milkshake
Hershey's Cookies 'N' Creme CHOCOLATE BAR
Hershey's Cookies and Cream Milkshake
Hershey's Creamy Milk CHOCOLATE BAR
Hershey's Dark CHOCOLATE BAR
Hershey's Exotic Dark Blueberry And Acai Chocolate Share Bag
Hershey's Exotic Dark Chocolate Californian Almonds - With Blackberry Crunchy Dark Chocolate
Hershey's Exotic Dark Pomegranate Chocolate
Hershey's Exotic Raspberry & Goji Dark Chocolate
Hershey's Kisses Almonds Chocolate
Hershey's Kisses Choco Truffle
Hershey's Kisses Cookies 'N' Cream Chocolate
Hershey's Kisses Hazelnut 'N' Cookies Chocolate
Hershey's Kisses Milk Chocolate
Hershey's Strawberry Milkshake
Hershey's Cocoa + Almond Spread
Hershey's Cocoa Powder
Horlicks Nutrition Drink Jar
Horlicks Women's Plus Caramel Drink Mix
Kellogg's Chocolate Muesli
Kellogg's Corn Flakes With Real Strawberry
Kellogg's Muesli Fruit Nut & Seeds 12-in-1 Power Breakfast
Kellogg's Multigrain Chocos
Kinder Creamy Milky And Cocoa With Extruded Rice
KOPIKO Cappuccino Coffee Candy
Lay's American Cream & Onion Potato Chips
Lay's Classic Salted Potato Chips
Lay's India's Magic Masala Potato Chips
Lay's Potato Chips - Sizzling Hot Spicy Flavour
Lay's Potato Chips WAFERstyle - Salt with Pepper Flavour
Lay's Spanish Tomato Tango Potato Chips
Lay's WAFERChips Red Chilli
Lay's West Indies Hot 'n' Sweet Chilli Potato Chips
Limca Lemon Soft Drink
Cocoa mass, sugar, cocoa butter, VANILLA CAKE
Lindt Excellence 70 % Cocoa Dark Chocolate
Lindt Excellence 90% Cocoa Supreme Dark CHOCOLATE BAR
Lindt Excellence Orange Intense Dark Chocolate
Lindt Exotic Milk Cornet Chocolate
Lindt Lindor Smooth Melting Assorted Chocolates Cornet
Lindt Swiss Classic Milk Chocolate
Lotte Coffy Bite Classic
Lotte Eclairs Coffy Bite Toffee
MAGGI 2-Minute Instant Noodles
Maggi Chicken Instant Noodles
Maggi Chilly Chow Cuppa Noodles
Maggi Korean BBQ Veg Instant Noodles
Maggi Masala Cuppa Noodles
Maggi Nutri-licious Masala Veg Atta Noodles
Maggi Special Masala Instant Noodles
Maltesers Chocolate
Mars Caramel CHOCOLATE BAR
McCain Mini Samosa - Cheese Corn
McCain Smile
Mcvitie's Digestive High Fibre Biscuits With Goodness Of Wholewheat
Mentos Chewy Dragees
Mentos Rainbow Assorted Flavour Chewy Toffee
Mentos Strawberry Flavour Toffee
Milka Raisins & Nuts Milk Chocolate
Nestle Milo Health Chocolate Drink with Millets
Mirinda Orange Flavoured Soft Drink
Mountain Dew Lemon Soft Drink
BRU Classic Cold Coffee Tetra Pack
Nescafe Cafe Style Iced Frappe Cold Coffee
Nescafe Ready To Drink Coffee Flavoured Milk Iced Latte Cold Coffee
Nescafe Ready To Drink Coffee Flavoured Milk Intense Cafe Cappucino Cold Coffee
Kitkat Delights Hazelnut
Nestle Cerelac Multigrain & Fruits Baby Food Cereal
Nestle Cerelac Wheat Apple Carrot Baby Food Cerea
Nestle KitKat Delights Caramel
Nestle KitKat Delights Dark
Nestle KitKat Delights Rich
Nestle Milkmaid Partly Skimmed Sweetened Condensed Milk
Nestle Munch Max Choco Coated Crunchy WAFERBar
Nutella Hazelnut Spread with Cocoa
Orbit Sugar-Free Mixed Fruit Chewing Gum Tube
Cadbury Chocobakes ChocLayered Cakes
Cadbury Chocobakes ChocoChip Cookies
Pillsbury Butterscotch Flavour Pancake Mix
Pillsbury Chocolate Flavour Pancake Mix 2-Minute Pancake Mix For Kids
Pillsbury VANILLA CAKE Custard Powder
Pringles Imported Potato Chips - Ranch
Pringles Imported Potato Crisps - BBQ
Pringles Potato Chips Desi Masala Tadka Flavour
Pringles Potato Chips Original Flavour
Pringles Potato Chips Original Flavour - Classic Salted
Pringles Potato Chips Peri Peri Flavour
Pringles Potato Chips Pizza Flavour
Pringles Potato Chips Tangy Tomato Twist
Quaker Oats Breakfast Cereal
Red Bull Energy Drink
Skittles Original Bite-Size Fruit Candy Tube
Skittles Wildberry Bite-Size Fruit Flavoured Candy
Snickers Almond Filled CHOCOLATE BAR
Snickers Filled with Brownie, Peanuts & Caramel CHOCOLATE BAR
Snickers Peanut Filled CHOCOLATE BAR Loaded with Delicious Roasted Peanuts
Sprite Lemon and Lime Soft Drink
Tabasco Red Pepper Sauce
Thums Up X Force
Tic Tac Candy - Red Apple Treat
Tic Tac Orange Hard Candy
Tic Tac Seeds Fennel (Saunf)
Tic Tac Seeds Jeera Blacksalt
Toblerone Black Chocolate
Toblerone Fruit & Nut Chocolate
Tropicana Delight Cranberry Fruit Juice
Tropicana Delight Guava Fruit Juice
Tropicana Delight Mixed Fruit Juice
Twix Minis Cookie Caramel Chocolate Pack
Wedel Milk CHOCOLATE BAR

In [31]:
# since cadbury and bournvita and highly confusing lets see what type of products are they??
# Search for brand names containing "CADB" OR "BOURN" OR "BOUENV"
cadbury_bournvita_rows = df[
    df['Brand_Name'].str.contains('CADB|BOURN|BOUENV', case=False, na=False)
]

# View specific columns
cadbury_bournvita_rows[['Brand_Name', 'Item name', 'Category']]

,Brand_Name,Item name,Category
3,BOUENVITA,Bournvita Biscuits,BISCUIT
5,BOURNVILLE,Cadbury Bournville Cranberry 50% Dark CHOCOLAT...,CHOCOLATE
6,BOURNVILLE,Cadbury Bournville Fruit & Nut 50% Dark CHOCOL...,CHOCOLATE
7,BOURNVILLE,Cadbury Bournville Rich Cocoa 70% Dark CHOCOLA...,CHOCOLATE
8,BOURNVILLE,Cadbury Temptations Almond Treat Premium CHOCO...,CHOCOLATE
9,BOURNVILLE,Cadbury Temptations Rum & Raisins Premium CHOC...,CHOCOLATE
10,CADBERY BORNVITA,Bournvita Chocolate,INSTANT FOOD
11,CADBURY,Cadbury 5 Star 3D CHOCOLATE BAR,CHOCOLATE
12,CADBURY,Cadbury 5 Star CHOCOLATE BAR,CHOCOLATE
13,CADBURY,Cadbury Bournville Rich Cocoa 50% Dark CHOCOLA...,CHOCOLATE
14,CADBURY,Cadbury Choclairs Gold Candy,CHOCOLATE
15,CADBURY,Cadbury Dairy Milk Bites Hazelnut Chocolate Pack,CHOCOLATE
16,CADBURY,Cadbury Dairy Milk Chocolate Bar,CHOCOLATE
17,CADBURY,Cadbury Dairy Milk Crispello CHOCOLATE BAR,CHOCOLATE
18,CADBURY,Cadbury Dairy Milk Fruit & Nut CHOCOLATE BAR,CHOCOLATE
19,CADBURY,Cadbury Dairy Milk Lickables Chocolate with Or...,CHOCOLATE
20,CADBURY,Cadbury Dairy Milk Silk Bubbly CHOCOLATE BAR,CHOCOLATE
21,CADBURY,Cadbury Dairy Milk Silk CHOCOLATE BAR,CHOCOLATE
22,CADBURY,Cadbury Dairy Milk Silk Desserts Brownie CHOCO...,CHOCOLATE
23,CADBURY,Cadbury Dairy Milk Silk Desserts Plum Cake CHO...,CHOCOLATE
24,CADBURY,Cadbury Dairy Milk Silk Hazelnut CHOCOLATE BAR,CHOCOLATE
25,CADBURY,Cadbury Dairy Milk Silk Mousse CHOCOLATE BAR,CHOCOLATE
26,CADBURY,Cadbury Dairy Milk Silk Oreo CHOCOLATE BAR,CHOCOLATE
27,CADBURY,Cadbury Fuse Mini Treats Chocolate Pack,CHOCOLATE
28,CADBURY,Cadbury Gems Chocolate Mini Treats Pack,CHOCOLATE
29,CADBURY,Cadbury Gems Surprise Ball Chocolate,CHOCOLATE
30,CADBURY,Cadbury Nutties Chocolate,CHOCOLATE
31,CADBURY,Cadbury Oreo Original Chocolatey Sandwich Bisc...,BISCUIT
32,CADBURY,Cadbury Perk Mini Treats Chocolate coated Wafers,CHOCOLATE

In [34]:
# 1. The Updated Typo Dictionary 
typo_map = {
    'HERSHYEYS': 'HERSHEYS',
    'BOUENVITA': 'CADBURY',
    'CADBERY BORNVITA': 'CADBURY',
    'BOURNVILLE': 'CADBURY', 
    'MOUMTAIN DEW': 'MOUNTAIN DEW',
    'DR OETKERS FUNFOODS': 'DR OETKER'
}

# 2. Clean the Brand_Name column in place
df['Brand_Name'] = df['Brand_Name'].replace(typo_map)

# 3. Save the cleaned dataframe to a new CSV file
df.to_csv(OUTPUT_CSV, index=False)

# 4. Verify that the typos are gone
print("Cleaned unique brands list:\n", df['Brand_Name'].unique())
print("\nTotal unique brands now:", df['Brand_Name'].nunique())

Cleaned unique brands list:
 <ArrowStringArray>
[                 '7 UP',          '7 UP NIMBOOZ',         'BETTY CROCKER',
               'CADBURY',                'BOUNTY',               'CHEETOS',
             'COKE ZERO', 'CONFETTERIA RAFFAELLO',             'DEL MONTE',
               'DORITOS',             'DR OETKER',             'DR PEPPER',
                 'FANTA',        'FERRERO ROCHER',                'GALAXY',
              'GATORADE',                'GODIVA',                'HARIBO',
              'HERSHEYS',              'HORLICKS',              'KELLOGGS',
            'KINDER JOY',                'KOPIKO',                 'LAY'S',
                 'LIMCA',                 'LINDT',                 'LOTTE',
                 'MAGGI',             'MALTESERS',                  'MARS',
                'MCCAIN',              'MCVITIES',                'MENTOS',
                 'MILKA',                  'MILO',               'MIRINDA',
          'MOUNTAIN DEW',               'NESCAFE',                'NESTLE',
               'NUTELLA',                 'ORBIT',                  'OREO',
             'PILLSBURY',              'PRINGLES',                'QUAKER',
              'RED BULL',              'SKITTLES',              'SNICKERS',
                'SPRITE',               'TABASCO',              'THUMS UP',
               'TIC TAC',             'TOBLERONE',             'TROPICANA',
                  'TWIX',                 'WEDEL']
Length: 56, dtype: str

Total unique brands now: 56

# VERIFYING THE NEW DATA

In [43]:
df_cleaned = pd.read_csv(OUTPUT_CSV)
print("Cleaned Brands list:")
print(df_cleaned['Brand_Name'].unique())

Cleaned Brands list:
<ArrowStringArray>
[                 '7 UP',          '7 UP NIMBOOZ',         'BETTY CROCKER',
               'CADBURY',                'BOUNTY',               'CHEETOS',
             'COKE ZERO', 'CONFETTERIA RAFFAELLO',             'DEL MONTE',
               'DORITOS',             'DR OETKER',             'DR PEPPER',
                 'FANTA',        'FERRERO ROCHER',                'GALAXY',
              'GATORADE',                'GODIVA',                'HARIBO',
              'HERSHEYS',              'HORLICKS',              'KELLOGGS',
            'KINDER JOY',                'KOPIKO',                 'LAY'S',
                 'LIMCA',                 'LINDT',                 'LOTTE',
                 'MAGGI',             'MALTESERS',                  'MARS',
                'MCCAIN',              'MCVITIES',                'MENTOS',
                 'MILKA',                  'MILO',               'MIRINDA',
          'MOUNTAIN DEW',               'NESCAFE',                'NESTLE',
               'NUTELLA',                 'ORBIT',                  'OREO',
             'PILLSBURY',              'PRINGLES',                'QUAKER',
              'RED BULL',              'SKITTLES',              'SNICKERS',
                'SPRITE',               'TABASCO',              'THUMS UP',
               'TIC TAC',             'TOBLERONE',             'TROPICANA',
                  'TWIX',                 'WEDEL']
Length: 56, dtype: str

In [44]:
# 3. Verify Cadbury absorbed everything (Bournvita, Bournville, etc.)
cadbury_rows = df_cleaned[df_cleaned['Brand_Name'] == 'CADBURY']
print(f"\nTotal CADBURY products after merge: {len(cadbury_rows)}")

Total CADBURY products after merge: 29

In [41]:
# Load raw vs cleaned to compare side-by-side
df_raw = pd.read_csv("data/multinational_brand_shortlist.csv")
df_clean = pd.read_csv("data/multinational_brand_cleaned.csv")

# Filter rows where the brand name was actually changed
changes = df_raw[df_raw['Brand_Name'] != df_clean['Brand_Name']]

# Display before vs after
print(f"Total Rows Corrected: {len(changes)}")
changes_summary = pd.DataFrame({
    'Original Brand (Raw)': df_raw.loc[changes.index, 'Brand_Name'],
    'Cleaned Brand (New)': df_clean.loc[changes.index, 'Brand_Name'],
    'Product Item Name': df_raw.loc[changes.index, 'Item name']
})

changes_summary.drop_duplicates(subset=['Original Brand (Raw)', 'Cleaned Brand (New)'])

Total Rows Corrected: 15

,Original Brand (Raw),Cleaned Brand (New),Product Item Name
3,BOUENVITA,CADBURY,Bournvita Biscuits
5,BOURNVILLE,CADBURY,Cadbury Bournville Cranberry 50% Dark CHOCOLAT...
10,CADBERY BORNVITA,CADBURY,Bournvita Chocolate
40,DR OETKERS FUNFOODS,DR OETKER,Dr. Oetker FunFoods Pizza Topping All-in-One S...
75,HERSHYEYS,HERSHEYS,Hershey's Cocoa + Almond Spread
123,MOUMTAIN DEW,MOUNTAIN DEW,Mountain Dew Lemon Soft Drink